export const TAGS_DATA = [
  { name: "ورزشی", slug: "sports" },
  { name: "فوتبال ایران", slug: "iranian-football" },
  { name: "فوتبال جهان", slug: "world-football" },
  { name: "اقتصادی", slug: "economy" },
  { name: "طلا و ارز", slug: "gold-and-currency" },
  { name: "بورس", slug: "stock-market" },
  { name: "خودرو", slug: "automotive" },
  { name: "مسکن و راه", slug: "housing-and-roads" },
  { name: "سیاسی", slug: "politics" },
  { name: "دولت", slug: "government" },
  { name: "مجلس", slug: "parliament" },
  { name: "انتخابات", slug: "elections" },
  { name: "بین‌الملل", slug: "international" },
  { name: "خاورمیانه", slug: "middle-east" },
  { name: "اروپا و آمریکا", slug: "europe-and-america" },
  { name: "اجتماعی", slug: "society" },
  { name: "حوادث", slug: "incidents" },
  { name: "محیط زیست", slug: "environment" },
  { name: "دادگاه و قضا", slug: "courts-and-judiciary" },
  { name: "علم و فناوری", slug: "science-and-technology" },
  { name: "اینترنت", slug: "internet" },
  { name: "هوش مصنوعی", slug: "artificial-intelligence" },
  { name: "سلامت و پزشکی", slug: "health-and-medicine" },
  { name: "دانشگاه و آموزش", slug: "university-and-education" },
  { name: "فرهنگ و هنر", slug: "culture-and-art" },
  { name: "سینما و تلویزیون", slug: "cinema-and-television" },
  { name: "موسیقی", slug: "music" },
  { name: "کتاب و ادبیات", slug: "books-and-literature" },
  { name: "گردشگری", slug: "tourism" },
];

export const TAGS_MAP = {
  sports: "ورزشی",
  "iranian-football": "فوتبال ایران",
  "world-football": "فوتبال جهان",
  economy: "اقتصادی",
  "gold-and-currency": "طلا و ارز",
  "stock-market": "بورس",
  automotive: "خودرو",
  "housing-and-roads": "مسکن و راه",
  politics: "سیاسی",
  government: "دولت",
  parliament: "مجلس",
  elections: "انتخابات",
  international: "بین‌الملل",
  "middle-east": "خاورمیانه",
  "europe-and-america": "اروپا و آمریکا",
  society: "اجتماعی",
  incidents: "حوادث",
  environment: "محیط زیست",
  "courts-and-judiciary": "دادگاه و قضا",
  "science-and-technology": "علم و فناوری",
  internet: "اینترنت",
  "artificial-intelligence": "هوش مصنوعی",
  "health-and-medicine": "سلامت و پزشکی",
  "university-and-education": "دانشگاه و آموزش",
  "culture-and-art": "فرهنگ و هنر",
  "cinema-and-television": "سینما و تلویزیون",
  music: "موسیقی",
  "books-and-literature": "کتاب و ادبیات",
  tourism: "گردشگری",
};
