export const TAGS_DATA = [
  { name: "ورزشی", slug: "sports" },
  { name: "فوتبال ایران", slug: "iranian-football" },
  { name: "فوتبال جهان", slug: "world-football" },
  { name: "اقتصادی", slug: "economy" },
  { name: "طلا و ارز", slug: "gold-and-currency" },
  { name: "بورس", slug: "stock-market" },
  { name: "خودرو", slug: "automotive" },
  { name: "مسکن و راه", slug: "housing-and-roads" },
  { name: "سیاسی", slug: "politics" },
  { name: "دولت", slug: "government" },
  { name: "مجلس", slug: "parliament" },
  { name: "انتخابات", slug: "elections" },
  { name: "بین‌الملل", slug: "international" },
  { name: "خاورمیانه", slug: "middle-east" },
  { name: "اروپا و آمریکا", slug: "europe-and-america" },
  { name: "اجتماعی", slug: "society" },
  { name: "حوادث", slug: "incidents" },
  { name: "محیط زیست", slug: "environment" },
  { name: "دادگاه و قضا", slug: "courts-and-judiciary" },
  { name: "علم و فناوری", slug: "science-and-technology" },
  { name: "اینترنت", slug: "internet" },
  { name: "هوش مصنوعی", slug: "artificial-intelligence" },
  { name: "سلامت و پزشکی", slug: "health-and-medicine" },
  { name: "دانشگاه و آموزش", slug: "university-and-education" },
  { name: "فرهنگ و هنر", slug: "culture-and-art" },
  { name: "سینما و تلویزیون", slug: "cinema-and-television" },
  { name: "موسیقی", slug: "music" },
  { name: "کتاب و ادبیات", slug: "books-and-literature" },
  { name: "گردشگری", slug: "tourism" },
];
